#!/bin/sh
#
USERNAME=user_tournify
PASSWORD=tournify
TABLES_DIR=../tables
CONSTRAINTS_DIR=../constraints

psql -U postgres -c "CREATE DATABASE tournify"
psql -U postgres -c "CREATE USER $USERNAME WITH PASSWORD '$password'"
psql -U user_tournify tournify -c "create sequence hibernate_sequence" #Needed for IDs generated by hibernate

for f in $TABLES_DIR/*.sql
do
  psql -U user_tournify tournify < $f
done

for f in $CONSTRAINTS_DIR/*.sql
do
  psql -U user_tournify tournify < $f
done